version: "3"

services:
  app:
    build:
      context: .
      args:
        DEV: "true"
    environment:
      - PYTHONPATH=/app
    ports:
      - "5050:5050"
    env_file:
        - path: ./.env
          required: true
    command: uvicorn main:app --reload --host 0.0.0.0 --port 5050
    volumes:
      - ./app:/app
    working_dir: /
